### ISSUE TITLE
RSS or regular email of links for subscribers

### ISSUE THREAD

**Issue by Tocacar** [LinkTuesday/Linktuesday.com#18]
It would be nice to be able to subscribe to an RSS feed for the site, or for a weekly, bi-weekly or monthly (whatever) email listing the links.  That way I wouldn't miss anything if I forgot to check the website.

**Comment by skoop** [comment]
OK, this project has been quiet for a while, but the feed has already been there for a long time: http://linktuesday.com/feed

**Comment by Tocacar** [comment]
Thank you for posting the link skoop.  I've added that to my feed now.
